# kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-attendance
  namespace: gimena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-attendance
  template:
    metadata:
      labels:
        app: content-attendance
    spec:
      containers:
      - name: content-attendance
        image: gimenac/attendance:2.0   # Reemplaza con tu imagen Docker
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials                # Nombre del Secret
              key: DATABASE_URL                         # Clave dentro del Secret
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_PASSWORD
