# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: gimena-ccoracc
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLW9kZC1icmVlemUtYTVuMnBmYXctcG9vbGVyLnVzLWVhc3QtMi5hd3MubmVvbi50ZWNoOjU0MzIvQXNpc3RlbmNpYT9zc2xtb2RlPXJlcXVpcmU=
  DATABASE_USERNAME: QXNpc3RlbmNpYV9vd25lcg==   # en Base64
  DATABASE_PASSWORD: SmxVT1Fxcks0RWky   # en Base64
#echo -n "JlUOQqrK4Ei2" | base64
#echo "ZGVtbzEyMw==" | base64 --deco