spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BodegaDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: Admin12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
